package br.com.pointel.jarch.mage;

import java.io.PrintStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.google.gson.Gson;
import br.com.pointel.jarch.data.DataClazz;
import br.com.pointel.jarch.data.Field;
import br.com.pointel.jarch.data.KeyForeign;
import br.com.pointel.jarch.data.KeyPrimary;
import br.com.pointel.jarch.data.Match;
import br.com.pointel.jarch.data.Nature;
import br.com.pointel.jarch.data.OrdName;
import br.com.pointel.jarch.data.Table;
import br.com.pointel.jarch.data.TableHead;
import br.com.pointel.jarch.data.Typed;

public class WizData {

    private static final Gson gson = new Gson();

    private WizData() {
    }

    public static String toChars(Object data) {
        return gson.toJson(data);
    }

    public static <T> T fromChars(String chars, Class<T> clazz) {
        return gson.fromJson(chars, clazz);
    }

    public static <T> T mapResult(ResultSet result, List<Typed> fieldList, Class<T> onClazz) throws Exception {
        var classes = WizData.getColumnsClasses(result);
        var values = WizData.getColumnsValues(result);
        try {
            var standardOne = onClazz.getConstructor(classes);
            return standardOne.newInstance(values);
        } catch (NoSuchMethodException e) {
            Nature[] natures;
            if (fieldList == null || fieldList.isEmpty()) {
                natures = WizData.getNaturesFrom(result);
            } else {
                natures = fieldList.stream().map(f -> f.type).toArray(Nature[]::new);
            }
            var bestOne = WizLang.getBestConstructor(onClazz, natures);
            if (bestOne == null) {
                bestOne = onClazz.getConstructor();
            }
            Object[] mappedArgs = new Object[bestOne.getParameterCount()];
            Class<?>[] paramTypes = bestOne.getParameterTypes();
            for (int i = 0; i < mappedArgs.length; i++) {
                mappedArgs[i] = WizData.getOn(values[i], paramTypes[i]);
            }
            var instance = onClazz.cast(bestOne.newInstance(mappedArgs));
            if (mappedArgs.length < values.length) {
                var columnsNames = WizData.getColumnsNames(result);
                for (int i = mappedArgs.length; i < values.length; i++) {
                    var columnName = columnsNames[i];
                    var field = onClazz.getDeclaredField(columnName);
                    var mappedField = WizData.getOn(values[i], field.getType());
                    WizLang.forceSetField(field, instance, mappedField);
                }
            }
            return instance;
        }
    }

    public static Table getTable(TableHead tableHead, Connection connection) throws Exception {
        var fieldList = new ArrayList<Field>();
        var keyPrimaryList = new ArrayList<KeyPrimary>();
        var keyForeignList = new ArrayList<KeyForeign>();
        var table = new Table(tableHead, fieldList, keyPrimaryList, keyForeignList);
        var meta = connection.getMetaData();
        var primaryRS = meta.getPrimaryKeys(tableHead.catalog, tableHead.schema, tableHead.name);
        while (primaryRS.next()) {
            var keyName = primaryRS.getString("PK_NAME");
            var keyPrimary = keyPrimaryList.stream()
                    .filter(p -> Objects.equals(p.name, keyName))
                    .findFirst().orElse(null);
            if (keyPrimary == null) {
                keyPrimary = new KeyPrimary(keyName, new ArrayList<>());
                keyPrimaryList.add(keyPrimary);
            }
            var sequence = primaryRS.getInt("KEY_SEQ");
            var columnName = primaryRS.getString("COLUMN_NAME");
            var keyColumn = new OrdName(sequence, columnName);
            keyPrimary.columnList.add(keyColumn);
        }
        var columnsRS = meta.getColumns(tableHead.catalog, tableHead.schema, tableHead.name, "%");
        while (columnsRS.next()) {
            final var fieldOrd = columnsRS.getInt("ORDINAL_POSITION");
            final var fieldName = columnsRS.getString("COLUMN_NAME");
            final var fieldNature = WizData.getNatureOfSQL(columnsRS.getInt("DATA_TYPE"));
            final var fieldSize = columnsRS.getInt("COLUMN_SIZE");
            final var fieldPrecision = columnsRS.getInt("DECIMAL_DIGITS");
            final var fieldNotNull = "NO".equals(columnsRS.getString("IS_NULLABLE"));
            final var fieldAutoIncrement = !"NO".equals(columnsRS.getString("IS_AUTOINCREMENT"));
            final var fieldAutoGenerated = !"NO".equals(columnsRS.getString("IS_GENERATEDCOLUMN"));
            final var fieldKeyPrimary = keyPrimaryList.stream().anyMatch(k -> k.columnList.stream().anyMatch(c -> Objects.equals(c.name, fieldName)));
            final var field = new Field(fieldOrd, fieldName, fieldNature, fieldSize, fieldPrecision, fieldNotNull, fieldAutoIncrement, fieldAutoGenerated, fieldKeyPrimary);
            field.setTable(table);
            fieldList.add(field);
        }
        var foreignRS = meta.getImportedKeys(tableHead.catalog, tableHead.schema, tableHead.name);
        while (foreignRS.next()) {
            var inName = foreignRS.getString("FK_NAME");
            var outName = foreignRS.getString("PK_NAME");
            var keyForeign = keyForeignList.stream()
                    .filter(f -> Objects.equals(f.inName, inName) && Objects.equals(f.outName, outName))
                    .findFirst().orElse(null);
            if (keyForeign == null) {
                var outCatalog = foreignRS.getString("PKTABLE_CAT");
                var outSchema = foreignRS.getString("PKTABLE_SCHEM");
                var outTable = foreignRS.getString("PKTABLE_NAME");
                var outTableHead = new TableHead(outCatalog, outSchema, outTable);
                keyForeign = new KeyForeign(inName, outName, outTableHead, new ArrayList<>());
                keyForeignList.add(keyForeign);
            }
            var sequence = foreignRS.getInt("KEY_SEQ");
            var inColumn = foreignRS.getString("FKCOLUMN_NAME");
            var outColumn = foreignRS.getString("PKCOLUMN_NAME");
            var match = new Match(sequence, inColumn, outColumn);
            keyForeign.matchList.add(match);
        }
        return table;
    }

    public static void printColumnsNamesAndNatures(ResultSet results) throws Exception {
        printColumnsNamesAndNatures(results, System.out);
    }

    public static void printColumnsNamesAndNatures(ResultSet results, PrintStream out) throws Exception {
        var meta = results.getMetaData();
        for (int i = 1; i <= meta.getColumnCount(); i++) {
            out.println(String.format("[%d] %s : %s",
                    i, meta.getColumnName(i), String.valueOf(WizData.getNatureOfSQL(meta.getColumnType(i)))));
        }
    }

    public static void printAllValues(ResultSet results) throws Exception {
        printAllValues(results, System.out);
    }

    public static void printAllValues(ResultSet results, PrintStream out) throws Exception {
        var count = results.getMetaData().getColumnCount();
        while (results.next()) {
            var line = new StringBuilder();
            for (int i = 1; i <= count; i++) {
                if (i > 1) {
                    line.append(" | ");
                }
                line.append(String.valueOf(results.getObject(i)));
            }    
            out.println(line.toString());
        }
    }

    public static String[] getColumnsNames(ResultSet results) throws Exception {
        var meta = results.getMetaData();
        var names = new String[meta.getColumnCount()];
        for (int i = 1; i <= names.length; i++) {
            names[(i - 1)] = meta.getColumnName(i);
        }
        return names;
    }

    public static Class<?>[] getColumnsClasses(ResultSet results) throws Exception {
        var meta = results.getMetaData();
        var classes = new Class<?>[meta.getColumnCount()];
        for (int i = 1; i <= classes.length; i++) {
            var className = meta.getColumnClassName(i);
            classes[(i - 1)] = Class.forName(className);
        }
        return classes;
    }

    public static Object[] getColumnsValues(ResultSet results) throws Exception {
        var meta = results.getMetaData();
        var values = new Object[meta.getColumnCount()];
        for (int i = 1; i <= values.length; i++) {
            values[(i - 1)] = results.getObject(i);
        }
        return values;
    }

    public static void setParams(PreparedStatement statement, Object[] params) throws Exception {
        for (int i = 0; i < params.length; i++) {
            statement.setObject(i + 1, params[i]);
        }
    }

    public static Nature[] getNaturesFrom(ResultSet results) throws Exception {
        var meta = results.getMetaData();
        var natures = new Nature[meta.getColumnCount()];
        for (int i = 1; i <= natures.length; i++) {
            natures[(i - 1)] = WizData.getNatureOfSQL(meta.getColumnType(i));
        }
        return natures;
    }

    public static Nature getNatureOfSQL(int jdbcType) {
        switch (jdbcType) {
            case 16: // BOOLEAN
                return Nature.Bool;
            case -7: // BIT
                return Nature.Bit;
            case -6: // TINYINT
                return Nature.Byte;
            case 5: // SMALLINT
                return Nature.Small;
            case 4: // INTEGER
                return Nature.Int;
            case -8: // ROWID
                return Nature.Serial;
            case -5: // BIGINT
                return Nature.Long;
            case 6: // FLOAT
                return Nature.Float;
            case 7: // REAL
                return Nature.Real;
            case 8: // DOUBLE
                return Nature.Double;
            case 2: // NUMERIC
                return Nature.Numeric;
            case 3: // DECIMAL
                return Nature.BigNumeric;
            case 1: // CHAR
            case -15: // NCHAR
            case -11: // NCHAR
                return Nature.Char;
            case 12: // VARCHAR
            case -1: // LONGVARCHAR
            case -9: // NVARCHAR
                return Nature.Chars;
            case 91: // DATE
                return Nature.Date;
            case 92: // TIME
                return Nature.Time;
            case 93: // TIMESTAMP
                return Nature.Timestamp;
            case 2013: // TIME_WITH_TIMEZONE
            case 2014: // TIMESTAMP_WITH_TIMEZONE
                return Nature.ZoneTime;
            case -2: // BINARY
            case -3: // VARBINARY
                return Nature.Bytes;
            case -4: // LONGVARBINARY
            case 2004: // BLOB
                return Nature.Blob;
            case -16: // LONGNVARCHAR
            case 2005: // CLOB
                return Nature.Text;
            case 1111: // OTHER
            case 2000: // OBJECT
                return Nature.Object;
            default:
                throw new UnsupportedOperationException("Could not identify the data nature of jdbc type: " + jdbcType);
        }
    }

    public static <T> T getOn(Object data, Class<T> onClass) throws Exception {
        if (data == null) {
            return null;
        }
        if (WizLang.isChildOf(onClass, Boolean.class)) {
            return onClass.cast(getOnBoolean(data));
        }
        throw new UnsupportedOperationException("Could not convert to " + onClass.getCanonicalName() + " from class: " + data.getClass().getCanonicalName());
    }

    public static Boolean getOnBoolean(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Boolean) {
            return (Boolean) data;
        }
        if (data instanceof Byte) {
            return (Byte) data != 0;
        }
        if (data instanceof Number number) {
            return number.intValue() != 0;
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.Bool, formatted, Boolean.class);
        }
        throw new Exception("Could not convert to Byte from class: " + data.getClass().getCanonicalName());
    }

    public static Byte getOnByte(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Byte) {
            return (Byte) data;
        }
        if (data instanceof Number number) {
            return number.byteValue();
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.Byte, formatted, Byte.class);
        }
        throw new Exception("Could not convert to Byte from class: " + data.getClass().getCanonicalName());
    }

    public static Short getOnShort(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Short) {
            return (Short) data;
        }
        if (data instanceof Number number) {
            return number.shortValue();
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.Small, formatted, Short.class);
        }
        throw new Exception("Could not convert to Short from class: " + data.getClass().getCanonicalName());
    }

    public static Integer getOnInteger(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Integer) {
            return (Integer) data;
        }
        if (data instanceof Number number) {
            return number.intValue();
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.Int, formatted, Integer.class);
        }
        throw new Exception("Could not convert to Integer from class: " + data.getClass().getCanonicalName());
    }

    public static Long getOnLong(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Long) {
            return (Long) data;
        }
        if (data instanceof Number number) {
            return number.longValue();
        }
        throw new Exception("Could not convert to Long from class: " + data.getClass().getCanonicalName());
    }

    public static Float getOnFloat(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Float) {
            return (Float) data;
        }
        if (data instanceof Number number) {
            return number.floatValue();
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.Float, formatted, Float.class);
        }
        throw new Exception("Could not convert to Float from class: " + data.getClass().getCanonicalName());
    }

    public static Double getOnDouble(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Double) {
            return (Double) data;
        }
        if (data instanceof Number number) {
            return number.doubleValue();
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.Double, formatted, Double.class);
        }
        throw new Exception("Could not convert to Double from class: " + data.getClass().getCanonicalName());
    }

    public static BigInteger getOnBigInteger(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof BigInteger) {
            return (BigInteger) data;
        }
        if (data instanceof Number number) {
            return new BigInteger(number.toString());
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.BigInt, formatted, BigInteger.class);
        }
        throw new Exception("Could not convert to BigInteger from class: " + data.getClass().getCanonicalName());
    }

    public static BigDecimal getOnBigDecimal(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof BigDecimal) {
            return (BigDecimal) data;
        }
        if (data instanceof Number number) {
            return new BigDecimal(number.toString());
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.BigNumeric, formatted, BigDecimal.class);
        }
        throw new Exception("Could not convert to BigDecimal from class: " + data.getClass().getCanonicalName());
    }

    public static Character getOnChar(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Character) {
            return (Character) data;
        }
        if (data instanceof Number number) {
            return (char) number.intValue();
        }
        if (data instanceof String formatted) {
            return getDataFormatted(Nature.Char, formatted, Character.class);
        }
        throw new Exception("Could not convert to Char from class: " + data.getClass().getCanonicalName());
    }

    public static String getOnString(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof String) {
            return (String) data;
        }
        if (WizLang.isChildOf(data.getClass(), java.util.Date.class)) {
            return WizUtilDate.format(java.util.Date.class.cast(data));
        }
        return String.valueOf(data);
    }

    public static java.time.Instant getOnInstant(Object data) throws Exception {
        return WizInstant.get(data);
    }

    public static java.time.ZonedDateTime getOnZonedDateTime(Object data) throws Exception {
        return WizZonedDateTime.get(data);
    }

    public static java.time.OffsetDateTime getOnOffsetDateTime(Object data) throws Exception {
        return WizOffsetDateTime.get(data);
    }

    public static java.time.OffsetTime getOnOffsetTime(Object data) throws Exception {
        return WizOffsetTime.get(data);
    }

    public static java.time.LocalDateTime getOnLocalDateTime(Object data) throws Exception {
        return WizLocalDateTime.get(data);
    }

    public static java.time.LocalDate getOnLocalDate(Object data) throws Exception {
        return WizLocalDate.get(data);
    }

    public static java.time.LocalTime getOnLocalTime(Object data) throws Exception {
        return WizLocalTime.get(data);
    }

    public static java.util.Date getOnUtilDate(Object data) throws Exception {
        return WizUtilDate.get(data);
    }

    public static java.sql.Date getOnSqlDate(Object data) throws Exception {
        return WizSqlDate.get(data);
    }

    public static java.sql.Time getOnSqlTime(Object data) throws Exception {
        return WizSqlTime.get(data);
    }

    public static java.sql.Timestamp getOnSqlTimestamp(Object data) throws Exception {
        return WizSqlTimestamp.get(data);
    }

    public static byte[] getOnBytes(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof byte[]) {
            return (byte[]) data;
        }
        throw new Exception("Could not convert to Bytes from class: " + data.getClass().getCanonicalName());
    }

    public static Blob getBlob(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Blob) {
            return (Blob) data;
        }
        throw new Exception("Could not convert to Blob from class: " + data.getClass().getCanonicalName());
    }

    public static Clob getClob(Object data) throws Exception {
        if (data == null) {
            return null;
        }
        if (data instanceof Clob) {
            return (Clob) data;
        }
        throw new Exception("Could not convert to Clob from class: " + data.getClass().getCanonicalName());
    }

    public static <T> T getDataFormatted(Nature nature, String formatted, Class<T> castTo) throws Exception {
        return castTo.cast(getDataFormatted(nature, formatted));
    }

    public static Object getDataFormatted(Nature nature, String formatted) throws Exception {
        if (formatted == null || formatted.isEmpty()) {
            return null;
        }
        switch (nature) {
            case Bool:
                return Boolean.parseBoolean(formatted);
            case Bit, Byte, Tiny:
                return Byte.parseByte(formatted);
            case Small:
                return Short.parseShort(formatted);
            case Int, Serial:
                return Integer.parseInt(formatted);
            case Long:
                return Long.parseLong(formatted);
            case Float:
            case Real:
                return Float.parseFloat(formatted);
            case Double:
                return Double.parseDouble(formatted);
            case BigInt, BigSerial:
                return new BigInteger(formatted);
            case Numeric, BigNumeric:
                return new BigDecimal(formatted);
            case Char:
                return formatted.charAt(0);
            case Chars, Text:
                return formatted;
            case Date:
                return WizUtilDate.parseDateMach(formatted);
            case Time:
                return WizUtilDate.parseTimeMach(formatted);
            case Timestamp:
                return WizUtilDate.parseTimestampMach(formatted);
            case Bytes:
            case Blob:
                return WizBytes.decodeFromBase64(formatted);
            case Object:
                return DataClazz.fromChars(formatted).getValue();
            default:
                throw new Exception("DataType Not Supported.");
        }
    }

    public static String formatData(Nature nature, Object data) throws Exception {
        if (data == null) {
            return "";
        }
        switch (nature) {
            case Bool:
            case Bit:
            case Byte:
            case Tiny:
            case Small:
            case Int:
            case Long:
            case BigInt:
            case Serial:
            case BigSerial:
            case Float:
            case Real:
            case Double:
            case Numeric:
            case BigNumeric:
            case Char:
            case Chars:
            case Text:
                return String.valueOf(data);
            case Date:
                return WizUtilDate.formatDateMach(WizUtilDate.get(data));
            case Time:
                return WizUtilDate.formatTimeMach(WizUtilDate.get(data));
            case DateTime:
                return WizUtilDate.formatDateTimeMach(WizUtilDate.get(data));
            case Timestamp:
                return WizUtilDate.formatTimestampMach(WizUtilDate.get(data));
            case Bytes:
            case Blob:
                return WizBytes.encodeToBase64(WizBytes.get(data));
            case Object:
                return new DataClazz(data).toChars();
            default:
                throw new Exception("DataType Not Supported.");
        }
    }

}
