package br.com.pointel.jarch.data;

import br.com.pointel.jarch.mage.WizData;

public class Field implements Data {

    public Integer ord;
    public String name;
    public Nature nature;
    public Integer size;
    public Integer precision;
    public Boolean notNull;
    public Boolean autoIncrement;
    public Boolean autoGenerated;
    public Boolean keyPrimary;

    private transient Table table;

    public Field() {
    }

    public Field(String name) {
        this.name = name;
    }

    public Field(Integer ord, String name) {
        this.ord = ord;
        this.name = name;
    }

    public Field(String name, Nature nature) {
        this.name = name;
        this.nature = nature;
    }

    public Field(Integer ord, String name, Nature nature) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
    }

    public Field(String name, Nature nature, Boolean notNull) {
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
    }

    public Field(Integer ord, String name, Nature nature, Boolean notNull) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
    }

    public Field(String name, Nature nature, Boolean notNull, Boolean keyPrimary) {
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    public Field(Integer ord, String name, Nature nature, Boolean notNull, Boolean keyPrimary) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    public Field(String name, Nature nature, Integer size) {
        this.name = name;
        this.nature = nature;
        this.size = size;
    }

    public Field(Integer ord, String name, Nature nature, Integer size) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
    }

    public Field(String name, Nature nature, Integer size, Boolean notNull) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.notNull = notNull;
    }

    public Field(Integer ord, String name, Nature nature, Integer size, Boolean notNull) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.notNull = notNull;
    }

    public Field(String name, Nature nature, Integer size, Integer precision) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
    }

    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
    }

    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
    }

    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
    }

    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean keyPrimary) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean keyPrimary) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.keyPrimary = keyPrimary;
    }

    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
    }

    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
    }

    public Field(String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary, Table table) {
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
        this.table = table;
    }

    public Field(Integer ord, String name, Nature nature, Integer size, Integer precision, Boolean notNull, Boolean autoIncrement, Boolean autoGenerated, Boolean keyPrimary, Table table) {
        this.ord = ord;
        this.name = name;
        this.nature = nature;
        this.size = size;
        this.precision = precision;
        this.notNull = notNull;
        this.autoIncrement = autoIncrement;
        this.autoGenerated = autoGenerated;
        this.keyPrimary = keyPrimary;
        this.table = table;
    }

    public String getReferenceName() {
        return table != null ? table.getReferenceName() + "." + name : name;
    }

    public Typed toTyped() {
        return new Typed(getReferenceName(), nature);
    }

    public Typed toTyped(String alias) {
        return new Typed(getReferenceName(), nature, alias);
    }

    public Valued toValued() {
        return new Valued(getReferenceName(), nature);
    }

    public Valued toValued(Object value) {
        return new Valued(getReferenceName(), nature, value);
    }

    public Table getTable() {
        return table;
    }

    public void setTable(Table table) {
        this.table = table;
    }

    @Override
    public boolean equals(Object that) {
        return this.deepEquals(that);
    }

    @Override
    public int hashCode() {
        return this.deepHash();
    }

    @Override
    public String toString() {
        return this.toChars();
    }

    public static Field fromChars(String chars) {
        return Data.fromChars(chars, Field.class);
    }
    
}
